@FunctionalValidation_HostAddress = http://localhost:5259

### Request to FluentValidation-based endpoint
POST {{FunctionalValidation_HostAddress}}/insurances/fluent
Accept: application/json
Content-Type: application/json

{
  "mainApplicant": {
    "firstName": "John",
    "lastName": "Smith",
    "dateOfBirth": "2020-01-02"
  },
  "policyDetails": {
    "startDate": "2025-12-31"
  },
  "hasRefusalProblem": true,
  "refusalYear": 2023,
  "refusalReason": "Reason for refusal"
}

### Request to FluentValidation-based endpoint when validation has been skipped
POST {{FunctionalValidation_HostAddress}}/insurances/fluent
Accept: application/json
Content-Type: application/json

{
  "mainApplicant": {
    "firstName": "John",
    "lastName": "Smith",
    "dateOfBirth": "2020-01-02"
  },
  "policyDetails": {
    "startDate": "2025-12-31"
  },
  "hasRefusalProblem": true,
  "refusalYear": null,
  "refusalReason": "Reason for refusal"
}

### Request to rigid functional validation endpoint
POST {{FunctionalValidation_HostAddress}}/insurances/functional-rigid
Accept: application/json
Content-Type: application/json

{
  "mainApplicant": {A
    "firstName": "John",
    "lastName": "Smith",
    "dateOfBirth": "2000-01-02"
  },
  "policyDetails": {
    "startDate": "2025-12-31"
  },
  "hasRefusalProblem": false
}

### Same rigid functional approach but with a Seq<ValidationError> instead of using Error's Monoid trait
POST {{FunctionalValidation_HostAddress}}/insurances/functional-rigid-seq
Accept: application/json
Content-Type: application/json

{
  "mainApplicant": {
    "firstName": "John",
    "lastName": "Smith",
    "dateOfBirth": "2000-01-02"
  },
  "policyDetails": {
    "startDate": "2025-12-31"
  },
  "hasRefusalProblem": false
}

###
